//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_VillageProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_signup
    {
        public int Id { get; set; }
        public string Your_Name { get; set; }
        public string Your_email { get; set; }
        public string password { get; set; }
        public string Repeat_password { get; set; }
        public string signdate { get; set; }
    }
}
